# AI News Event Clustering & Timeline Builder

## Problem Statement

In today's digital world, the same real-world event is reported by hundreds of news articles across different platforms and time periods. This makes it difficult to identify the actual event, understand how it evolved over time, and track its key milestones.

This project aims to build an AI-powered system that automatically groups related news articles into real-world events, constructs chronological event timelines, assigns meaningful event labels, and generates concise summaries describing the evolution of each event.

---

## Project Workflow

#### Phase 1: Data Loading & Preprocessing

#### Phase 2: Semantic Embeddings

#### Phase 3: Event Clustering

#### Phase 4: Event Labeling

#### Phase 5: Timeline Construction

#### Phase 6: Milestone Detection

#### Phase 7: Event Story Generation

#### Phase 8: Visualization Dashboard

## Phase 1: Data Loading & Preprocessing

#### 1.1 Import Required Libraries

In [2]:
# Install Libraries
!pip install sentence-transformers hdbscan umap-learn nltk

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Requirement already satisfied: hdbscan in /usr/local/lib/python3.12/dist-packages (0.8.43)
Requirement already satisfied: umap-learn in /usr/local/lib/python3.12/dist-packages (0.5.12)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan) (1.5.3)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn) (0.6.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51.2->umap-learn) (0.43.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.6)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.15)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

#### 1.2 Dataset Upload

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#### 1.3 Dataset Extraction

In [ ]:
import zipfile

zip_path = '/content/drive/MyDrive/AI_News_Event_Project/articles1.csv.zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content')

print("Dataset extracted successfully")

Dataset extracted successfully

#### 1.4 Dataset Loading

In [ ]:
df = pd.read_csv('/content/articles1.csv')
print("Dataset Shape:", df.shape)

Dataset Shape: (50000, 10)

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/AI_News_Event_Project/articles1.csv",
    index=False)
print("CSV saved permanently to Google Drive")

CSV saved permanently to Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv(
    '/content/drive/MyDrive/AI_News_Event_Project/articles1.csv')

print(df.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(50000, 10)

In [ ]:
df.head()

,Unnamed: 0,id,title,publication,author,date,year,month,url,content
0,0,17283,House Republicans Fret About Winning Their Hea...,New York Times,Carl Hulse,2016-12-31,2016.0,12.0,NaN,WASHINGTON — Congressional Republicans have...
1,1,17284,Rift Between Officers and Residents as Killing...,New York Times,Benjamin Mueller and Al Baker,2017-06-19,2017.0,6.0,NaN,"After the bullet shells get counted, the blood..."
2,2,17285,"Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...",New York Times,Margalit Fox,2017-01-06,2017.0,1.0,NaN,"When Walt Disney’s “Bambi” opened in 1942, cri..."
3,3,17286,"Among Deaths in 2016, a Heavy Toll in Pop Musi...",New York Times,William McDonald,2017-04-10,2017.0,4.0,NaN,"Death may be the great equalizer, but it isn’t..."
4,4,17287,Kim Jong-un Says North Korea Is Preparing to T...,New York Times,Choe Sang-Hun,2017-01-02,2017.0,1.0,NaN,"SEOUL, South Korea — North Korea’s leader, ..."

#### 1.5 Dataset Audit

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   50000 non-null  int64
 1   id           50000 non-null  int64
 2   title        50000 non-null  object
 3   publication  50000 non-null  object
 4   author       43694 non-null  object
 5   date         50000 non-null  object
 6   year         50000 non-null  float64
 7   month        50000 non-null  float64
 8   url          0 non-null      float64
 9   content      50000 non-null  object
dtypes: float64(3), int64(2), object(5)
memory usage: 3.8+ MB

In [ ]:
df.columns.tolist()

['Unnamed: 0',
 'id',
 'title',
 'publication',
 'author',
 'date',
 'year',
 'month',
 'url',
 'content']

In [ ]:
df.describe(include='all')

,Unnamed: 0,id,title,publication,author,date,year,month,url,content
count,50000.000000,50000.000000,50000,50000,43694,50000,50000.000000,50000.000000,0.0,50000
unique,NaN,NaN,49920,5,3603,983,NaN,NaN,NaN,49888
top,NaN,NaN,The 10 most important things in the world righ...,Breitbart,Breitbart News,2016-08-22,NaN,NaN,NaN,advertisement
freq,NaN,NaN,7,23781,1559,221,NaN,NaN,NaN,42
mean,25694.378380,44432.454800,NaN,NaN,NaN,NaN,2016.273700,5.508940,NaN,NaN
std,15350.143677,15773.615179,NaN,NaN,NaN,NaN,0.634694,3.333062,NaN,NaN
min,0.000000,17283.000000,NaN,NaN,NaN,NaN,2011.000000,1.000000,NaN,NaN
25%,12500.750000,31236.750000,NaN,NaN,NaN,NaN,2016.000000,3.000000,NaN,NaN
50%,25004.500000,43757.500000,NaN,NaN,NaN,NaN,2016.000000,5.000000,NaN,NaN
75%,38630.250000,57479.250000,NaN,NaN,NaN,NaN,2017.000000,8.000000,NaN,NaN
max,53291.000000,73469.000000,NaN,NaN,NaN,NaN,2017.000000,12.000000,NaN,NaN

In [ ]:
df.describe()

         Unnamed: 0            id          year         month  url
count  50000.000000  50000.000000  50000.000000  50000.000000  0.0
mean   25694.378380  44432.454800   2016.273700      5.508940  NaN
std    15350.143677  15773.615179      0.634694      3.333062  NaN
min        0.000000  17283.000000   2011.000000      1.000000  NaN
25%    12500.750000  31236.750000   2016.000000      3.000000  NaN
50%    25004.500000  43757.500000   2016.000000      5.000000  NaN
75%    38630.250000  57479.250000   2017.000000      8.000000  NaN
max    53291.000000  73469.000000   2017.000000     12.000000  NaN

#### 1.6 Missing Value Analysis

In [ ]:
# Missing values count
df.isnull().sum()

Unnamed: 0         0
id                 0
title              0
publication        0
author          6306
date               0
year               0
month              0
url            50000
content            0
dtype: int64

#### 1.7 Duplicate Analysis

In [ ]:
# Total duplicate rows
df.duplicated().sum()

np.int64(0)

#### 1.8 Date Analysis

In [ ]:
# Check date column
df['date'].head()

0    2016-12-31
1    2017-06-19
2    2017-01-06
3    2017-04-10
4    2017-01-02
Name: date, dtype: object

In [ ]:
# Convert date to datetime
df['date'] = pd.to_datetime(
    df['date'],
    errors='coerce')

In [ ]:
# Check date range
print("Earliest Date :", df['date'].min())
print("Latest Date   :", df['date'].max())

Earliest Date : 2011-11-22 00:00:00
Latest Date   : 2017-06-21 00:00:00

In [ ]:
# Number of unique publication dates
df['date'].nunique()

983

#### 1.9 Data Cleaning

In [ ]:
# Keep only useful columns
df = df[['title', 'content', 'date']]

In [ ]:
# Missing values count
df.isnull().sum()

title      0
content    0
date       0
dtype: int64

In [ ]:
print(df.shape)

(50000, 3)

#### 1.10 Text Preparation

In [ ]:
# Combine title and content
df['clean_text'] = (
    df['title'].astype(str)
    + " "
    + df['content'].astype(str))

In [ ]:
df[['title', 'clean_text']].head()

,title,clean_text
0,House Republicans Fret About Winning Their Hea...,House Republicans Fret About Winning Their Hea...
1,Rift Between Officers and Residents as Killing...,Rift Between Officers and Residents as Killing...
2,"Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...","Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ..."
3,"Among Deaths in 2016, a Heavy Toll in Pop Musi...","Among Deaths in 2016, a Heavy Toll in Pop Musi..."
4,Kim Jong-un Says North Korea Is Preparing to T...,Kim Jong-un Says North Korea Is Preparing to T...

#### 1.11 Text Normalization

In [ ]:
import re

def clean_text(text):
    text = str(text)

    text = text.lower()

    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'\t', ' ', text)

    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [ ]:
df['clean_text'] = df['clean_text'].apply(clean_text)

In [ ]:
df[['clean_text']].head()

                                          clean_text
0  house republicans fret about winning their hea...
1  rift between officers and residents as killing...
2  tyrus wong, ‘bambi’ artist thwarted by racial ...
3  among deaths in 2016, a heavy toll in pop musi...
4  kim jong-un says north korea is preparing to t...

In [ ]:
df.to_csv(
    '/content/drive/MyDrive/AI_News_Event_Project/processed_articles.csv',
    index=False)

In [ ]:
!git clone https://github.com/KattaSrichakra/AI-News-Event-Clustering-and-Timeline-Builder.git
%cd AI-News-Event-Clustering-and-Timeline-Builder

fatal: destination path 'AI-News-Event-Clustering-and-Timeline-Builder' already exists and is not an empty directory.
/content/AI-News-Event-Clustering-and-Timeline-Builder

In [ ]:
!pwd

/content/AI-News-Event-Clustering-and-Timeline-Builder

In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/AI_News_Event_Clustering_and_Timeline_Builder.ipynb" .

In [ ]:
!ls

AI_News_Event_Clustering_and_Timeline_Builder.ipynb  README.md
LICENSE						     test.txt

In [ ]:
TOKEN = ""

In [ ]:
import os

os.system(
    f'git remote set-url origin https://KattaSrichakra:{TOKEN}@github.com/KattaSrichakra/AI-News-Event-Clustering-and-Timeline-Builder.git')

0

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	AI_News_Event_Clustering_and_Timeline_Builder.ipynb

nothing added to commit but untracked files present (use "git add" to track)

In [ ]:
!git add .

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   AI_News_Event_Clustering_and_Timeline_Builder.ipynb

In [ ]:
!git commit -m "Completed Phase 1 data loading and preprocessing"

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@fbe81fa83f14.(none)')

In [ ]:
!git config --global user.name "KattaSrichakra"
!git config --global user.email "kattasrichakra@gmail.com"

In [ ]:
!git commit -m "Completed Phase 1 data loading and preprocessing"

[main 06f400d] Completed Phase 1 data loading and preprocessing
 1 file changed, 1 insertion(+)
 create mode 100644 AI_News_Event_Clustering_and_Timeline_Builder.ipynb

In [ ]:
!git push origin main

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 48.41 KiB | 3.72 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/KattaSrichakra/AI-News-Event-Clustering-and-Timeline-Builder.git
   1363146..06f400d  main -> main

# Phase 2: Semantic Embeddings

In this phase, news articles are transformed into dense vector representations using Sentence Transformers. These embeddings capture semantic meaning and help identify related news events.

#### 2.1 Sampling Strategy

In [ ]:
sample_df = df.sample(
    n=10000,
    random_state=42
).reset_index(drop=True)

print("Sample Shape:", sample_df.shape)

Sample Shape: (10000, 4)

In [ ]:
sample_df.head()

,title,content,date,clean_text
0,"US-led strike caused civilian deaths in Mosul,...","Irbil, Iraq (CNN) A coalition airstrike on an ...",2017-03-26,"us-led strike caused civilian deaths in mosul,..."
1,EU Gave Notre Dame Hammer Attack Jihadi Award ...,The ‘Islamic ’ Notre Dame hammer attacker was...,2017-06-07,eu gave notre dame hammer attack jihadi award ...
2,"At Golden Globes Afterparties, Stars Applaud M...","At the Golden Globes afterparties, hoi polloi ...",2017-01-10,"at golden globes afterparties, stars applaud m..."
3,Election Eve Poll in Georgia’s Sixth Congressi...,Republican Karen Handel leads Democrat Jon Oss...,2017-06-19,election eve poll in georgia’s sixth congressi...
4,Romney says Trump will be open-minded,Washington (CNN) During the presidential campa...,2016-12-17,romney says trump will be open-minded washingt...

#### 2.2 Save Sample Dataset

In [ ]:
sample_df.to_csv(
    '/content/drive/MyDrive/AI_News_Event_Project/sample_10000.csv',
    index=False)

print("Sample dataset saved successfully")

NameError: name 'sample_df' is not defined

In [4]:
sample_df = pd.read_csv(
    '/content/drive/MyDrive/AI_News_Event_Project/sample_10000.csv')

print("Sample dataset loaded successfully")

Sample dataset loaded successfully

#### 2.3 Install Required Libraries

In [5]:
!pip install -q sentence-transformers

#### 2.4 Load Sentence Transformer Model

In [6]:
from sentence_transformers import SentenceTransformer

In [ ]:
model = SentenceTransformer(
    'all-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

#### 2.5 Generate Semantic Embeddings

In [ ]:
embeddings = model.encode(
    sample_df['clean_text'].tolist(),
    batch_size=32,
    show_progress_bar=True)

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

In [ ]:
print("Embedding Shape:", embeddings.shape)

Embedding Shape: (10000, 384)

#### 2.6 Save Embeddings

In [ ]:
np.save(
    '/content/drive/MyDrive/AI_News_Event_Project/embeddings_10000.npy',
    embeddings)

print("Embeddings saved successfully")

Embeddings saved successfully

In [7]:
!git clone https://github.com/KattaSrichakra/AI-News-Event-Clustering-and-Timeline-Builder.git

Cloning into 'AI-News-Event-Clustering-and-Timeline-Builder'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 2), reused 6 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (11/11), 52.10 KiB | 8.68 MiB/s, done.
Resolving deltas: 100% (2/2), done.

In [8]:
%cd AI-News-Event-Clustering-and-Timeline-Builder

/content/AI-News-Event-Clustering-and-Timeline-Builder

In [ ]:
!git config --global user.name "KattaSrichakra"
!git config --global user.email "kattasrichakra@g"